POST http://localhost:8080/users
Content-Type: application/json

{
    "id": 20,
    "name": "s"
}

### 로케일
GET http://localhost:8080/internationalized
Accept-Language: kr

### version
GET http://localhost:8080/admin/v1/users/1
Accept: application/vnd.company.appv1+json
Accept-Language: kr

### JPA method
DELETE http://localhost:8080/users/4

### JPA method
GET http://localhost:8080/users/4

### JPA
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "chandler",
  "password" : "1234",
  "ssn" : "111-1111"
}

### 게시글 등록
POST http://localhost:8080/users/1/posts
Content-Type: application/json

{
  "description": "게시글 1"
}
